src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <description>External ID related to Foundation</description>
        <externalId>true</externalId>
        <label>AVB Account ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AVB_Contact_Name__c</fullName>
        <label>AVB Associate (First &amp; Last Name)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Primary_Type__c</fullName>
        <description>**NOTE***  THE APPROVAL PROCESSES ARE BUILT AROUND THE PICKLIST ITEMS RELATED TO ADJ CASES.   As a result this field is very sensitive.  Please do not update without using great caution.</description>
        <label>Case Primary Type</label>
        <picklist>
            <controllingField>Reason</controllingField>
            <picklistValues>
                <fullName>30 Day Move-In Guarantee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accept with Conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate Adjustment per Policy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate Lease Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Refund of Money Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Wire Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complaint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correction of Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Double Charged Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect Final Billing Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Late Fee Waived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease Termination Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move-In Pro-Rate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notice to Vacate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSF Notification Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Amenity Fee Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Incorrect MTM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Waive MTM Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reservation Fees</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/MyPagingController.cls
public with sharing class MyPagingController {

    //Sorting
    private String sortDirection = 'ASC';
    private String sortExp = 'CaseNumber';


private List<Case> cases;

private List<Case> pageCases;

private Integer pageNumber;

private Integer pageSize;

private Integer totalPageNumber;

public Integer getPageNumber()
{

return pageNumber; 

}

public String sortField {get; set;}

public String previousSortField {get; set;}


public List<Case> getCases()

{

return pageCases;

}


public Integer getPageSize()

{

return pageSize;

}


public Boolean getPreviousButtonEnabled()

{

return !(pageNumber > 1);

}


public Boolean getNextButtonDisabled()

{

if (cases == null) return true;

else

return ((pageNumber * pageSize) >= cases.size());

}


public Integer getTotalPageNumber()

{

if (totalPageNumber == 0 && cases !=null)

{

totalPageNumber = cases.size() / pageSize;

Integer mod = cases.size() - (totalPageNumber * pageSize);

if (mod > 0)

totalPageNumber++;

}


return totalPageNumber;

}


public MyPagingController()

{

pageNumber = 0;

totalPageNumber = 0;

pageSize = 5;

ViewData();

}


public PageReference ViewData()

{ 

cases = null;

totalPageNumber = 0;

BindData(1);

return null;

}


private void BindData(Integer newPageIndex)

{

try

{


if (cases == null)

cases = [select CaseNumber, Account.Name, Account.Account_ID__c, Status,Reason, Case_Primary_Type__c, Owner.Alias, AVB_Contact_Name__c from Case where IsClosed= false and Owner.ProfileId =  '00e60000000r2eO' order by CaseNumber];



pageCases = new List<Case>();


Transient Integer counter = 0;

Transient Integer min = 0;

Transient Integer max = 0;


if (newPageIndex > pageNumber)

{

min = pageNumber * pageSize;

max = newPageIndex * pageSize;

}

else

{

max = newPageIndex * pageSize;

min = max - pageSize;


}



for(Case c : cases)

{

counter++;

if (counter > min && counter <= max) 

pageCases.add(c);

}


pageNumber = newPageIndex;


if (pageCases == null || pageCases.size() <= 0)

ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Data not available for this view.'));

}

catch(Exception ex)

{

ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,ex.getMessage()));

}


}


public PageReference nextBtnClick() {


BindData(pageNumber + 1);

return null;

}


public PageReference previousBtnClick() {


BindData(pageNumber - 1);

return null;

}

public void doSort(){
    String order = 'asc';
    
    /*This checks to see if the same header was clicked two times in a row, if so, it switches the order.*/
    if(previousSortField == sortField) {
        order = 'desc';
        previousSortField = null;
        }
        else {
            previousSortField = sortField;
            }
            
        //To sort the table we simply need to use this one line, nice!
        superSort.sortList(cases,sortField,order);
        }

    
}