src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <description>External ID related to Foundation</description>
        <externalId>true</externalId>
        <label>AVB Account ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Affordable_Housing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Affordable Housing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Amount_Due_Next_FOM__c</fullName>
        <label>Amount Due Next FOM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Associate_Housing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Associate Housing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Block_E_Payment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Block e-Payment\Lockbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Community_ID__c</fullName>
        <label>Community ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Community_Name__c</fullName>
        <description>This field is denormalized to be available on the Customer Group Page to enable a formula to dynamically build a document store directory.  This field should be eliminated as soon as SFDC allows cross-references in formulas - e.g. Parent ID.Name. and can be used to form the directory path.</description>
        <label>Community Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Court_Date__c</fullName>
        <inlineHelpText>Community&apos;s Court Date for Litigation Activities - This field will be updated on a monthly basis.</inlineHelpText>
        <label>Court Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Current_Balance__c</fullName>
        <label>Current Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_Collections_Updated__c</fullName>
        <label>Date Collections Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Sent_To_Collections__c</fullName>
        <label>Date Sent To Collections</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Forwarding_Address_City__c</fullName>
        <description>Populated from MRI</description>
        <label>Fwd Address - City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Forwarding_Address_Country__c</fullName>
        <label>Fwd Address - Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Forwarding_Address_Line_1__c</fullName>
        <description>Populated from MRI</description>
        <label>Fwd Address - Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Forwarding_Address_Line_2__c</fullName>
        <description>Populated from MRI</description>
        <label>Fwd Address - Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Forwarding_Address_State__c</fullName>
        <description>Populated from MRI</description>
        <label>Fwd Address - State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Forwarding_Address_Zip__c</fullName>
        <description>Populated from MRI</description>
        <label>Fwd Address - Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Late_Count__c</fullName>
        <label>Late Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSF_Count__c</fullName>
        <label>NSF Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Refresh_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>DO NOT DELETE - Flag used by the Real time Sync process. Please do not ever delete!!!</description>
        <label>Refresh Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applicant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co-Resident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Old</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resident</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unique_Record_Id__c</fullName>
        <description>Concatenation of community code and customer group account number to uniquely identify a customer group that belong to multiple communities during upsert processes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Use NameGroup when entering prospects.
Example: HO06010536</inlineHelpText>
        <label>Unique Record Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Write_Offs__c</fullName>
        <label>Write Offs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <description>External ID</description>
        <externalId>true</externalId>
        <label>Customer ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prior_Resident__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox will be used to identify contacts (customers) that have been deleted from Foundation.</description>
        <inlineHelpText>This checkbox flags customers who were deleted from Foundation as Prior.</inlineHelpText>
        <label>Prior Resident</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unique_Record_Id__c</fullName>
        <description>Concatenation of customer group account number and customer ID to result in a unique record ID that can be used during the upsert process.</description>
        <externalId>true</externalId>
        <label>Unique Record Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Customer_Group_to_Unit_Relationships__c.object
<CustomObject>
    <description>AVB Custom Object - This is a join table to allow many to many relationships between Customer Groups (Accounts) and Units.</description>
    <fields>
        <fullName>Unique_Record_Id__c</fullName>
        <description>Concatenation of customer group account number and unique unit ID to provide a unique record ID that can be used during upserting.</description>
        <externalId>true</externalId>
        <label>Unique Record Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipName>Customer_Group_to_Unit_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Group Units</label>
    <nameField>
        <displayFormat>Unit-{000000}</displayFormat>
        <label>Customer Group to Unit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Group Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Litigation_Data__c.object
<CustomObject>
    <description>Custom object to store the Litigations data.</description>
    <fields>
        <fullName>Account_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N60000001Z2t9EAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Court_Date__c</fullName>
        <label>Court Date</label>
        <type>DateTime</type>
    </fields>
    <label>Litigation Data</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Litigation Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litigations Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Litigation_Notes__c.object
<CustomObject>
    <description>AVB Custom Object - This object shows as a related list under the Litigation Activies object.  The purpose of this object is to update the status of the Litigation Activity and add Notes\comments.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attorney confirmed cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney confirmed filed with court</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney confirmed NTQ served</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autocreated Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Community</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled/other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled/Paid in Full</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled/Partial Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled/Sent in error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled/Skipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled/Vacated/Moved Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consent Judgement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversation with Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversation with Resident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Default Judgment entered/Received Judgment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emailed Community</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evicted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holdover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Important Note</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Judgement Absolute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Judgment Executed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Judgment Satisfied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Fees Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locked Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nuisance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Court Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Eviction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Lock Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Warrant/Warrant Filed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prior Resident</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Litigation Note</label>
    <nameField>
        <displayFormat>Note-{0}</displayFormat>
        <label>Litigation Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litigation Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Real_Time_Sync_Log__c.object
<CustomObject>
    <description>Object used to record the error logs generated during real time sync process.</description>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Code__c</fullName>
        <label>Error Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Real Time Sync Log</label>
    <nameField>
        <displayFormat>Log-{00000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Real Time Sync Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <description>AVB Custom Object - This object will be loaded with Unit reference data from Foundation and subsequently related to Customer Group Accounts via a join table - Customer Group Units - to allow an account to have multiple Units.</description>
    <fields>
        <fullName>Affordable_Housing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Affordable Housing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unit ID</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Unit</label>
    <nameField>
        <label>PBU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RealTimeAccountUpdate.cls
global class RealTimeAccountUpdate {
	
	static boolean writeLog(String avbAccID, String code, String message) {
    	try {
	      	Real_Time_Sync_Log__c log = new Real_Time_Sync_Log__c();
	        log.Account_Number__c = avbAccID;
	        log.Error_Code__c = code;
	        log.Error_Message__c = message;

	        insert log;
	        return true;
		} catch (Exception e) {
			return false;
		}
    }
    
    webService static boolean upsertData(String avbAccID, Account acc, Contact[] contacts, Customer_Group_to_Unit_Relationships__c[] custGroupUnits) {
    	try {
	    	updateAccount(acc);
	    	if (contacts.size() > 0) {
	    		upsert contacts;
	    	}
	    	if (custGroupUnits.size() > 0) {
	    		upsert custGroupUnits;
	    	}
    	} catch (Exception e) {
            writeLog(avbAccID,'','Failed to upsert data' + e.getMessage());
			return false; 
        }
        return true;
    }
    
   	webService static boolean upsertLtData(String avbAccID,Litigation_Data__c[] litigationData) {
    	try {
    		System.debug('creating litigation data ' + avbAccID + litigationData.size());
	    	if (litigationData.size() > 0) {
	    		List<Database.upsertResult> uResults = Database.upsert(litigationData, false);
				List<Litigation_Data__c> ltIds = new List<Litigation_Data__c>();
				for (Database.upsertResult result:uResults) {
					System.debug('ids for delete ' + result.isSuccess() + result.getId());
					if (result.isSuccess()) {
         				ltIds.add(new Litigation_Data__c(Id=result.getId()));
					}
     			}
     			if (ltIds.size() > 0) {
     				delete ltIds;
     			}
	    	}
    	} catch (Exception e) {
            writeLog(avbAccID,'','Failed to upsert litigation data' + e.getMessage());
			return false; 
        }
        return true;
    }   	
	    
	webService static String[] upsertUnits(String avbAccID, Unit__c[] units) {
		String[] ids = new String[]{};
        try {
        	List<Database.upsertResult> uResults = Database.upsert(units, true);
        	for(Database.upsertResult result:uResults) {
         		 ids.add(result.getId());
      		}
        } catch (Exception e) {
            writeLog(avbAccID,'','Failed to Upsert Units:'+e.getMessage());
        }
        return ids;
    }
			
	webService static boolean updateRefreshFlag(Account acct) {
		try {
			Account newAcc = new Account(Id = acct.Id, Refresh_Flag__c = acct.Refresh_Flag__c);
        	update newAcc;
        } catch (Exception e) {
        	writeLog(acct.Account_ID__c,'','Failed to update Refresh flag:'+e.getMessage());
            return false;
	   	}
	    return true;
	}

	static boolean updateAccount(Account acct) {
		try {
			Account newAcc = new Account(Id = acct.Id, Status__c=acct.Status__c, Affordable_Housing__c=acct.Affordable_Housing__c,
							Associate_Housing__c=acct.Associate_Housing__c, Community_Name__c=acct.Community_Name__c,
							Community_ID__c=acct.Community_ID__c, Late_Count__c=acct.Late_Count__c, NSF_Count__c=acct.NSF_Count__c,
							ParentId=acct.ParentId, Amount_Due_Next_FOM__c=acct.Amount_Due_Next_FOM__c, 
							Current_Balance__c=acct.Current_Balance__c, 
							Name=acct.Name, Type=acct.Type,
							Account_ID__c=acct.AccountNumber,
							Forwarding_Address_Line_1__c=acct.Forwarding_Address_Line_1__c,
							Forwarding_Address_Line_2__c=acct.Forwarding_Address_Line_2__c,
							Forwarding_Address_City__c=acct.Forwarding_Address_City__c,
							Forwarding_Address_State__c=acct.Forwarding_Address_State__c,
							Forwarding_Address_Zip__c=acct.Forwarding_Address_Zip__c,
							Forwarding_Address_Country__c=acct.Forwarding_Address_Country__c,
							Block_E_Payment__c=acct.Block_E_Payment__c,
							Write_Offs__c=acct.Write_Offs__c,
							Date_Sent_To_Collections__c=acct.Date_Sent_To_Collections__c,
							Date_Collections_Updated__c=acct.Date_Collections_Updated__c);
			if (acct.Unique_Record_ID__c != null) {
				newAcc.Unique_Record_ID__c = acct.Unique_Record_ID__c;
			}				
        	update newAcc;
        } catch (Exception e) {
        	writeLog(acct.Account_ID__c,'','Failed to update Acc:'+e.getMessage());
            return false;
	   	}
	    return true;
	}

	webService static Account[] queryCommunity(String communityID) {
		//Account acc = new Account();
		Account[] comm = [select Id, Court_Date__c from Account where RecordTypeId=:'012600000000n1g' and Community_ID__c=:communityID];		
		return comm;
	}
	
	webService static Contact[] queryContacts(String accountId) {
		Contact[] contacts = [select Id, Customer_ID__c,Prior_Resident__c from contact where AccountId =:accountId];
		return contacts;
	}
	
	webService static List<Unit__c[]> queryUnits(String commId) {
		List<Unit__c[]> units = new List<Unit__c[]>();
		for (Unit__c[] u : [select Id, Unit_ID__c from unit__c where Community__c = :commId]) {
			units.add(u);
		}
		return units;
	}
	
	webService static Customer_Group_to_Unit_Relationships__c[] queryCGUnits(String accID) {
		Customer_Group_to_Unit_Relationships__c[] cgus = [select Id,Unit__c,Customer_Group__c,Unique_Record_Id__c from Customer_Group_to_Unit_Relationships__c where (Customer_Group__c=:accID)];
		return cgus;
	}
	
	//Starting test methods//
	static testMethod void test_writeLog() {
		System.assertEquals(true, writeLog('AVB_Test_001','1','Error occurred.'));
	}
	
	static testMethod void test_upsertData() {
		Account acc = [select Id, Account_ID__c from Account limit 1];
		Id aid = acc.Id;
		Contact[] contacts = [select Id from Contact limit 2];
		Customer_Group_to_Unit_Relationships__c[] cgUnits = [select Id from Customer_Group_to_Unit_Relationships__c limit 2];
		Litigation_Data__c[] ltData = [select Id from Litigation_Data__c limit 2];
		System.assertEquals(true, upsertData('AVB_Test_001', acc, contacts, cgUnits));
	}
		
	static testMethod void test_upsertLitigationData() {
		Litigation_Data__c t = new Litigation_Data__c();
        t.Litigation_Flag_FND__c = true;
        t.Law_Firm__c = 'Mallios, Rider, & Goley, LLP';
        t.Account_ID__c = [select Id,Community_ID__c,Account_ID__c from Account where RecordTypeId=:'012600000000n1b' limit 1].Id;
        t.Original_Amount__c = 1000.00;
        t.Litigation_Notes__c = 'test';

		Litigation_Data__c[] ltData = new Litigation_Data__c[]{};
		ltData.add(t);
		System.assertEquals(true, upsertLtData('AVB_Test_001', ltData));

		//Litigation_Data__c t2 = new Litigation_Data__c();//[select Id, Account_ID__c, Litigation_Flag_FND__c,Litigation_Notes__c,Litigation_Closure_Reason__c from Litigation_Data__c limit 1];
        t.Litigation_Flag_FND__c = false;
        t.Litigation_Notes__c = 'test';
        t.Litigation_Closure_Reason__c = 'paid';
        t.Law_Firm__c = 'Mallios, Rider, & Goley, LLP';
		t.Original_Amount__c = 100.00;
		t.Last_Modified_Date_Time_in_Foundation__c = System.now();
		t.Last_Modified_By_Foundation_User__c = 'test';
		//t.Account_ID__c = [select Id,Community_ID__c,Account_ID__c from Account where RecordTypeId=:'012600000000n1b' limit 1].Id;

		Litigation_Data__c[] ltData2 = new Litigation_Data__c[]{};
		ltData2.add(t);
		System.assertEquals(true, upsertLtData('AVB_Test_001', ltData2));
	}
		
	static testMethod void test_updateAcc() {		
		Account acc = new Account(name='Testing Account');
		
		test.startTest();
		insert acc;
		
		Account acc1 = [select Id, Account_ID__c, Status__c, Affordable_Housing__c,
							Associate_Housing__c, Community_Name__c,
							Community_ID__c, Late_Count__c, NSF_Count__c,
							ParentId, Amount_Due_Next_FOM__c, 
							Current_Balance__c, Unique_Record_ID__c, 
							Name, Type,
							Forwarding_Address_Line_1__c,
							Forwarding_Address_Line_2__c,
							Forwarding_Address_City__c,
							Forwarding_Address_State__c,
							Forwarding_Address_Zip__c,
							Forwarding_Address_Country__c,
							Block_E_Payment__c/*,
							Write_Offs__c,
							Date_Sent_To_Collections__c,
							Date_Collections_Updated__c */
							from Account where id = :acc.id];	

		System.assertEquals(true, updateAccount(acc));
	}
	
	static testMethod void test_updateAccount() {
		Account acc = [select Id, Refresh_Flag__c from Account limit 1];
		System.debug('acc flag ' + acc.Refresh_Flag__c);
		acc.Refresh_Flag__c=false;
		System.assertEquals(true, updateRefreshFlag(acc));		
	}
	
	static testMethod void test_upsertUnits() {
		Unit__c[] units = [select Id from Unit__c limit 2];
		String[] ids = upsertUnits('AVB_Test_001', units);
		System.assert(2 == ids.size());
	}
	
	static testMethod void queryCommunity() {
		String commId = [select Id,Community_ID__c from Account where RecordTypeId =: '012600000000n1g' limit 1].Community_ID__c;
		Account[] comm = queryCommunity(commId);
		System.assert(1 == comm.size());

		if (comm.size() == 1) {
			String accId = comm[0].Id;
			Contact[] contacts = queryContacts(accId);
			System.assert(contacts.size() == contacts.size());
			
			List<Unit__c[]> units = queryUnits(commId);
			System.assert(units.size() == units.size());
			
			String cgId = [select Id from Account where RecordTypeId=:'012600000000n1b' limit 1].Id;
			Customer_Group_to_Unit_Relationships__c[] cgus = queryCGUnits(cgId);
			System.assert(cgus.size() == cgus.size());
		}
	}
}