src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Eblast_Audience_Distribution_list__c</fullName>
        <description>Determines how to set SF report to filter out email addresses</description>
        <inlineHelpText>Ex.  All residents, Buildings 1-9, etc.  This information will always be obtained right from Salesforce.</inlineHelpText>
        <label>eBlast Audience/Distribution</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Case_Issue__c.object
<CustomObject>
    <description>This object is used to track the individual charges and credits on each case.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Financial_Adjustments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Affordable Housing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate Feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate Housing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avalon Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AvalonBay.com (Parent Company)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AvalonCommunities.com</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community/Lease Policies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Recovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Landlord Tenant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leasing Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move Out Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parking/Storage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Security Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subsidy Accounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suggestions - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor Recovery</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Charge_Type__c</fullName>
        <label>Charge Type</label>
        <picklist>
            <picklistValues>
                <fullName>Accelerated Rent/400500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alarm Fees/422200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Fee/420400</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAM Charges/430300</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAM Reconcilliation/430300</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cert of Occ./206000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clubhouse/Com Room/420600</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Rent/430100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Common Area Ameni/420200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Premium/470100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card Fee/422300</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Srv Disc/545250</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Damage Receipts/561200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Term Rent/420900</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guest Apartment/420700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Reconciliation/430300</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance/430300</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ista conversion/207000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Late Charges/420300</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Costs/Evicti/601600</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Notices/601600</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Prep Fees/601600</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lock/Key Charge/570800</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minol Final  Bill/530500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MTM/421400</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Res Parking/425500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Qualified Income/424900</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Utilities/539000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parking Rent/421300/430400</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parking Sales Tax/790400/205900</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subcategory__c</fullName>
        <label>Subcategory</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Applicant Remains on Saferent Denial List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applicant Removed from Saferent Denial List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate Priority - Relinquish Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clubhouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concierge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emailed PAF and License Agreement for Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fitness Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Associate Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HVAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indoor Common Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Landscaping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Late Rent - Re-instate Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Late Rent - Revocation Warning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Late Rent - Revoke Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOA - Re-instate Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Documents Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move-In Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notice to Vacate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outdoor Common Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAF and License Agreement Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAF Signed and Returned - Revoke Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pest Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plumbing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pool</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Charge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Issue</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Development_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>General settings that apply to custom development</description>
    <fields>
        <fullName>Can_Copy_Associates_on_Cases__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines whether a user can use the &quot;Copy Associate&quot; section on the Combined Case Edit screen. If a user does not match to any TRUE setting records, they will not see &quot;Copy Associates&quot; on the page.</description>
        <inlineHelpText>Determines whether a user can use the &quot;Copy Associate&quot; section on the Combined Case Edit screen. If a user does not match to any TRUE setting records, they will not see &quot;Copy Associates&quot; on the page.</inlineHelpText>
        <label>Can Copy Associates on Cases</label>
        <type>Checkbox</type>
    </fields>
    <label>Development Settings</label>
</CustomObject>

src/classes/Ext_CaseIssues.cls
public class Ext_CaseIssues {

	Case thisCase;
	//public list<Case_Issue__c> issues { get; set; }
	public list<extIssue> xissues { get; set; }
	
	//Can this user copy associates?
	public Boolean CanCopyAssociates { get; private set; }
	
	//number of Case Issues to display on combined page
	Integer NumIssuesOnPage = 5;
	
	public CaseComment newComment { get; set; }
	public list<SelectOption> addresseeOptions { get; private set; }
	
	public Ext_CaseIssues(ApexPages.standardController stdcon)
	{
		if (thisCase == null)
		{
			thisCase = (Case)stdcon.getRecord();
		}
		makeCaseIssues();
		makeAddresseeOptions();
		newComment = new CaseComment();
		
		//Make CanCopyAssociates selective wrt the user's Development_Settings__c Custom Setting
		CanCopyAssociates = FALSE;
		if (Development_Settings__c.getInstance().Can_Copy_Associates_on_Cases__c == TRUE)
			CanCopyAssociates = TRUE;
			
	}
	
	public class extIssue
	{
		public Case_Issue__c issue { get; set; }
		
		public Boolean WillCreateTask { get; set; }
		public Boolean WillSendEmail { get; set; }
		public Task NewTask { get; set; }
		public list<Id> addresseeIds { get; set; } //user Ids to address email
		public String additionalEmails { get; set; } //additional email addresses to use
		public Boolean IsEditable { get; set; }
		
		public extIssue(Case_Issue__c ci)
		{
			this.issue = ci;
			this.NewTask = new Task();
			this.WillSendEmail = FALSE;
			this.WillCreateTask = FALSE;
		}
	}
	
	private void makeAddresseeOptions()
	{
		addresseeOptions = new list<SelectOption>();
		
		//set of user role ids for this user and anyone directly above them in the hierarchy
		set<id> roleidsUserAndAbove = new set<Id>();
		
		//get all user roles
		map<Id, UserRole> allRolemap = new map<Id, UserRole>([
			select Id, ParentRoleId 
			from UserRole]);
		Id parentId;
		if (Userinfo.getUserRoleId() != null)
		{
			UserRole thisUserRole = allRolemap.get(Userinfo.getUserRoleId());
			parentId = thisUserRole.parentRoleId;
			
			//add the user's own role to the set of roleids to query on	
			roleidsUserAndAbove.add(thisUserRole.Id);
		}
		
		//collect all user roles up the tree until there's a role with no parent role
		while (parentId != null)
		{
			//save the parentId we have
			roleidsUserAndAbove.add(parentId);
			
			//move up the tree one step
			parentId = allRolemap.get(parentId).parentRoleId;
		}
		
		//query for all users that are either in roles above this user, or have CSO or Legal in their title
		list<User> addresseeUsers = [select Id, FirstName, LastName, Title 
			from User 
			where UserRoleId in :roleidsUserAndAbove
				or Title like '%CSO%'
				or Title like '%Legal%'];
		
		//construct addresseeOptions list
		for (User u : addresseeUsers)
		{
			String optionName = '';
			
			if (u.FirstName != null) optionName += u.FirstName + ' ';
			optionName += u.LastName;
			if (u.Title != null) optionName += ', ' + u.Title;
			
			addresseeOptions.add(new SelectOption(u.Id, optionName));
		}		
	}
	
	private void makeCaseIssues()
	{
		Id caseid;
		list<Case_Issue__c> issues = new list<Case_Issue__c>();
		xissues = new list<extIssue>();
		
		if (thisCase.Id != null)
		{
			caseid = thisCase.Id;
			issues = [select Id, Category__c, Subcategory__c, Amount__c, Type__c, Charge_Type__c, Notes__c
				from Case_Issue__c
				where Case__c = :thisCase.Id];
			
			for (Case_Issue__c ci : issues)
			{
				extIssue newxissue = new extIssue(ci);
				newxissue.IsEditable = FALSE;
				xissues.add(newxissue);
			}
		}
		
		//how many blank lines to add to page? Depends on how many issues there are already
		Integer NumBlankIssues = NumIssuesOnPage - issues.size();
		
		//add at least one no matter what
		if (NumBlankIssues < 1)
			NumBlankIssues = 1;
			
		//populate list up to max
		Integer counter = 0;
		for (Integer i = 0; i < NumBlankIssues; i++)
		{
			Case_Issue__c newissue = new Case_Issue__c();
			issues.add(newissue);
			extIssue newxissue = new extIssue(newissue);
			newxissue.IsEditable = TRUE;
			xissues.add(newxissue);
			counter++;
		}
	}
	
	public PageReference saveCase()
	{
		PageReference pageref = null;
		//save case
		//fulfill requirement for this field in sandbox environment
		Case eblastCase = new Case();
		if (thisCase.Id != null)
		{
			eblastCase = [select Eblast_Audience_Distribution_list__c
				from Case
				where Id = :thisCase.Id];
		}
		if (eblastCase.Eblast_Audience_Distribution_list__c == null)
			thisCase.Eblast_Audience_Distribution_list__c = 'required text';
		
		try
		{
			database.upsert(new list<Case> { thisCase });
			
			//save case issues
			saveIssues();
			
			//make Tasks
			makeTasks();
			
			//send emails (copy associates)
			sendEmails();
			
			//save case comment
			if (newComment.CommentBody != null)
			{
				CaseComment commenttoinsert = new CaseComment(
					ParentId = thisCase.Id,
					CommentBody = newComment.CommentBody);
				insert commenttoinsert;
			}
			
			pageref = new PageReference('/' + thisCase.Id);
		}
		catch (Exception e)
		{
			ApexPages.addMessages(e);
		}
		
		return pageref;
	}
	
	private void makeTasks()
	{
		//go through case issues
		list<Task> taskstoinsert = new list<Task>();
		for (extIssue xi : xissues)
		{
			if (xi.WillCreateTask)
			{
				xi.NewTask.ActivityDate = system.today();
				xi.NewTask.WhatId = thisCase.Id;
				taskstoinsert.add(xi.NewTask);
			}
		}
		
		if (taskstoinsert.size() > 0)
		{
			insert taskstoinsert;
		}
	}
	
	private void sendEmails()
	{
		//get Email Template
		list<EmailTemplate> templates = [select Id 
			from EmailTemplate 
			where Name != null 
			limit 1];
		if (templates.size() > 0)
		{
			//collect email addresses for selected Users
			set<Id> userids = new set<Id>();
			for (extIssue xi : xissues)
			{
				if (xi.WillSendEmail)
					userids.addall(xi.addresseeIds);
			}
			map<Id, User> userid2usermap = new map<Id, User>([select Id, Email 
				from User 
				where Id in :userids]);
				
			//Construct email messages (one for each checked Case Issue)
			list<Messaging.SingleEmailMessage> emailstosend = new list<Messaging.SingleEmailMessage>();
			list<Task> taskstoinsert = new list<Task>();
			for (extIssue xi : xissues)
			{
				String namelist = '';
				if (xi.WillSendEmail)
				{
					list<String> emailaddresses = new list<String>();
					for (Id userid : xi.addresseeIds)
					{
						User u = userid2usermap.get(userid);
						emailaddresses.add(u.Email);
						namelist += u.FirstName + ' ' + u.LastName + ', ';
					}
					emailaddresses.addAll(xi.additionalEmails.split(';'));
					
					Messaging.SingleEmailMessage newemail = new Messaging.SingleEmailMessage();
					newemail.setToAddresses(emailaddresses);
					newemail.setWhatId(thisCase.Id);
					newemail.setTemplateId(templates[0].Id);
					
					emailstosend.add(newemail);
				
					//save Email as Completed Task on Case
					String descrip = 'Copy Associate email sent on Case  Sent to: ' + namelist + system.today().format() + '.';
					
					Task newtask = new Task(
						WhatId = thisCase.Id,
						Status = 'Complete',
						ActivityDate = system.today(),
						Subject = 'Email',
						Description = descrip);
					taskstoinsert.add(newtask);
				}
				
			}
			
			//send email list
			Messaging.sendEmail(emailstosend);
			
			
			
		} //end if templates size > 0
	}
	
	public PageReference saveIssues()
	{
		PageReference pageref = null;
		if ((thisCase != null)
			&& (thisCase.Id != null))
		{
			list<Case_Issue__c> cistoupsert = new list<Case_Issue__c>();
			
			for (extIssue xi : xissues)
			{
				Case_Issue__c ci = xi.issue;
				if (ci.Category__c != null)
				{
					Case_Issue__c newci = new Case_Issue__c(
						Id = ci.Id,
						Case__c = thisCase.Id,
						Category__c = ci.Category__c,
						Subcategory__c = ci.Subcategory__c,
						Type__c = ci.Type__c,
						Notes__c = ci.Notes__c,
						Charge_Type__c = ci.Charge_Type__c);
					cistoupsert.add(newci);
				}
			}
			if (cistoupsert.size() > 0)
			{
system.debug('\n\n87 cistoupsert ' + cistoupsert);			
				database.upsert(cistoupsert);
			}
			pageref = new PageReference('/' + thisCase.Id);
		}
		return pageref;
	}
	
	public PageReference addRow()
	{
		PageReference pageref = null;
		Case_Issue__c newissue = new Case_Issue__c();
		//issues.add(newissue);
		extIssue newxissue = new extIssue(newissue);
		newxissue.IsEditable = TRUE;
		xissues.add(newxissue);
	
		return pageref;
	}
}