src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AVB_Contact_Name__c</fullName>
        <label>AVB Associate (First &amp; Last Name)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Primary_Type__c</fullName>
        <description>**NOTE***  THE APPROVAL PROCESSES ARE BUILT AROUND THE PICKLIST ITEMS RELATED TO ADJ CASES.   As a result this field is very sensitive.  Please do not update without using great caution.</description>
        <label>Case Primary Type</label>
        <picklist>
            <controllingField>Reason</controllingField>
            <picklistValues>
                <fullName>30 Day Move-In Guarantee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accept with Conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate Adjustment per Policy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate Lease Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Refund of Money Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Wire Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complaint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correction of Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Double Charged Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect Final Billing Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Late Fee Waived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease Termination Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move-In Pro-Rate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notice to Vacate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSF Notification Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Amenity Fee Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Incorrect MTM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Waive MTM Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reservation Fees</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expected_MoveIn_Date__c</fullName>
        <label>Expected Move-In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Move_Out_Date__c</fullName>
        <label>Move Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NTV_Date__c</fullName>
        <label>Notice to Vacate Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Preliminary_Inspection_Date__c</fullName>
        <label>Preliminary Inspection Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Rejected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>hidden field used by Apex Trigger when evaluating rejected status</description>
        <label>Rejected</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/Case_MoveInMoveOutTrigTest.cls
@isTest
private class Case_MoveInMoveOutTrigTest {
    //MoveInMoveOut move = new MoveInMoveOut();

    static testmethod void testNewMoveIn()
    {
        //New Move In
        Account acc = [select id from Account limit 1];
        User u = [select id from User where IsActive = true limit 1];
        Case WorkingCase = new Case(
                RecordTypeID = MoveInMoveOut.casertmap().get('Move In Tracking Process'),
                AccountID = acc.id,
                Origin = 'MRI Import',
                Status = 'New',
                Priority = 'Medium',
                Rejected__c = False,
                Reason = 'Move In',
                Case_Primary_Type__c = 'Move In',
                Expected_MoveIn_Date__c = system.today().addDays(10),
                OwnerID = u.id,
                AVB_Contact_Name__c = 'MRI Import'
            );
test.startTest();       
        insert WorkingCase;
                    
test.stopTest();
        list<Task> tasks = [select id from Task where WhatID = :WorkingCase.id and IsClosed != true and AVB_Type__c = 'Move In Process'];
        system.assertEquals(3, tasks.size());
        
    }
    
    static testmethod void testStatusChange()
    {
        //Status Change pass-through
        Account acc = [select id from Account limit 1];
        User u = [select id from User where IsActive = true limit 1];
        Case WorkingCase = new Case(
                RecordTypeID = MoveInMoveOut.casertmap().get('Move Out Tracking Process'),
                AccountID = acc.id,
                Origin = 'MRI Import',
                Status = 'New',
                Priority = 'Medium',
                Rejected__c = False,
                Reason = 'Notice To Vacate',
                Case_Primary_Type__c = 'Notice To Vacate',
                NTV_Date__c = system.today().addDays(-1),
                Move_Out_Date__c = system.today().addDays(10),
                Preliminary_Inspection_Date__c = system.now().addDays(5),
                OwnerID = u.id,
                AVB_Contact_Name__c = 'MRI Import'
            );
        
        insert WorkingCase;
        list<Task> tasks = [select id from Task where WhatID = :WorkingCase.id and IsClosed != true and AVB_Type__c = 'Move Out Process'];
        system.assertEquals(4, tasks.size()); //4 open Tasks on new Move Out
        
        WorkingCase.Status = 'Open'; //Case must be Open to be in Move Out

test.StartTest();       
        update WorkingCase;
test.stopTest();

        tasks = [select id from Task where WhatID = :WorkingCase.id and IsClosed != true and AVB_Type__c = 'Move Out Process'];
        system.assertEquals(4, tasks.size()); //still 4, should not have affected Tasks
        
    }


    static testmethod void testCancelMoveIn()
    {
        //Cancel Move In
        Account acc = [select id from Account limit 1];
        User u = [select id from User where IsActive = true limit 1];
        Case WorkingCase = new Case(
                RecordTypeID = MoveInMoveOut.casertmap().get('Move In Tracking Process'),
                AccountID = acc.id,
                Origin = 'MRI Import',
                Status = 'New',
                Priority = 'Medium',
                Rejected__c = False,
                Reason = 'Move In',
                Case_Primary_Type__c = 'Move In',
                Expected_MoveIn_Date__c = system.today().addDays(10),
                OwnerID = u.id,
                AVB_Contact_Name__c = 'MRI Import'
            );
        
        insert WorkingCase;
        
        WorkingCase.Status = 'Open'; //Case must be Open to be in Move Out
        update WorkingCase;
        list<Task> tasks = [select id from Task where WhatID = :WorkingCase.id and IsClosed != true and AVB_Type__c = 'Move In Process'];
        system.assertEquals(3, tasks.size());//New Move In
        
        WorkingCase.Reason = 'Cancelled';
        WorkingCase.Status = 'Closed';

test.startTest();
        update WorkingCase;
test.stopTest();    
        tasks = [select id from Task where WhatID = :WorkingCase.id and IsClosed != true and AVB_Type__c = 'Move In Process'];
system.debug('\n\nWorkingCase ' + WorkingCase + '\ntasks ' + tasks);        
        system.assertEquals(0, tasks.size());//Should all be closed now
        
    }
    
    static testmethod void testReschedMoveIn()
    {
        //Reschedule Move In
        Account acc = [select id from Account limit 1];
        User u = [select id from User where IsActive = true limit 1];
        Case WorkingCase = new Case(
                RecordTypeID = MoveInMoveOut.casertmap().get('Move In Tracking Process'),
                AccountID = acc.id,
                Origin = 'MRI Import',
                Status = 'New',
                Priority = 'Medium',
                Rejected__c = False,
                Reason = 'Move In',
                Case_Primary_Type__c = 'Move In',
                Expected_MoveIn_Date__c = system.today().addDays(10),
                OwnerID = u.id
                //AVB_Contact_Name__c = cgu.?
            );
        
        insert WorkingCase;
        
        WorkingCase.Status = 'Open'; //Case must be Open to be in Move Out
        update WorkingCase;
        list<Task> tasks = [select id from Task where WhatID = :WorkingCase.id and IsClosed != true and AVB_Type__c = 'Move In Process'];
        system.assertEquals(3, tasks.size());//New Move In
        
        WorkingCase.Expected_MoveIn_Date__c = system.today().addDays(20);
test.startTest();
        update WorkingCase;
test.stopTest();    
        tasks = [select id from Task where WhatID = :WorkingCase.id and IsClosed != true and AVB_Type__c = 'Move In Process'];
        system.assertEquals(3, tasks.size());// Move In
            
    }
    
    static testmethod void testBadNewMoveIn()
    {
        //New Move In
        Account acc = [select id from Account limit 1];
        User u = [select id from User where IsActive = true limit 1];
        Case WorkingCase = new Case(
                RecordTypeID = MoveInMoveOut.casertmap().get('Move In Tracking Process'),
                AccountID = acc.id,
                Origin = 'MRI Import',
                Status = 'New',
                Priority = 'Medium',
                Rejected__c = False,
                Reason = 'Move In',
                Case_Primary_Type__c = 'Move In',
                Expected_MoveIn_Date__c = null,
                OwnerID = u.id,
                AVB_Contact_Name__c = 'MRI Import'
            );
test.startTest();       
        insert WorkingCase;
                    
test.stopTest();
        list<Task> tasks = [select id, ActivityDate from Task where WhatID = :WorkingCase.id and IsClosed != true and AVB_Type__c = 'Move In Process'];
        system.assertEquals(3, tasks.size());
        system.assertEquals(system.today(),tasks[0].ActivityDate); //Dates set to today, because there's no move in date.
        
    }
    
    static testmethod void testNewMoveOut()
    {
        //New Move Out
        Account acc = [select id from Account limit 1];
        User u = [select id from User where IsActive = true limit 1];
        Case WorkingCase = new Case(
                RecordTypeID = MoveInMoveOut.casertmap().get('Move Out Tracking Process'),
                AccountID = acc.id,
                Origin = 'MRI Import',
                Status = 'New',
                Priority = 'Medium',
                Rejected__c = False,
                Reason = 'Notice To Vacate',
                Case_Primary_Type__c = 'Notice To Vacate',
                NTV_Date__c = system.today().addDays(-1),
                Move_Out_Date__c = system.today().addDays(10),
                Preliminary_Inspection_Date__c = system.now().addDays(5),
                OwnerID = u.id,
                AVB_Contact_Name__c = 'MRI Import'
            );
        
test.StartTest();       
        insert WorkingCase;
test.stopTest();        
        list<Task> tasks = [select id, ActivityDate, Subject_Sub_Category__c from Task where WhatID = :WorkingCase.id and IsClosed != true and AVB_Type__c = 'Move Out Process'];
        system.assertEquals(4, tasks.size()); //2 open Tasks on new Move Out
        for (Task t : tasks) {
            if (t.Subject_Sub_Category__c == 'Notice to Vacate Follow-up') 
            	system.assertEquals(WorkingCase.NTV_Date__c.addDays(2), t.ActivityDate);
            if (t.Subject_Sub_Category__c == 'Final Move Out Inspection/Estimates Inquiry') 
            	system.assertEquals(WorkingCase.Preliminary_Inspection_Date__c.date().addDays(2), t.ActivityDate);
            if (t.Subject_Sub_Category__c == 'Move Out Packet/Process Inquiry') 
            	system.assertEquals(WorkingCase.NTV_Date__c.addDays(4), t.ActivityDate);
            if (t.Subject_Sub_Category__c == 'Move Out Complete Follow Up') 
            	system.assertEquals(WorkingCase.Move_Out_Date__c.addDays(3), t.ActivityDate);
        }            
    }
    
    static testmethod void testCancelMoveOut()
    {
        //Cancel Move Out
        Account acc = [select id from Account limit 1];
        User u = [select id from User where IsActive = true limit 1];
        Case WorkingCase = new Case(
                RecordTypeID = MoveInMoveOut.casertmap().get('Move Out Tracking Process'),
                AccountID = acc.id,
                Origin = 'MRI Import',
                Status = 'New',
                Priority = 'Medium',
                Rejected__c = False,
                Reason = 'Notice To Vacate',
                Case_Primary_Type__c = 'Notice To Vacate',
                NTV_Date__c = system.today().addDays(-1),
                Move_Out_Date__c = system.today().addDays(10),
                Preliminary_Inspection_Date__c = system.now().addDays(5),
                OwnerID = u.id,
                AVB_Contact_Name__c = 'MRI Import'
            );
        
        
        insert WorkingCase;
        
        list<Task> tasks = [select id from Task where WhatID = :WorkingCase.id and IsClosed != true and AVB_Type__c = 'Move Out Process'];
        system.assertEquals(4, tasks.size()); //4 open Tasks on new Move Out
        
        WorkingCase.Status = 'Open'; //Case must be Open to be in Move Out
        update WorkingCase;
        tasks = [select id from Task where WhatID = :WorkingCase.id and IsClosed != true and AVB_Type__c = 'Move Out Process'];
        system.assertEquals(4, tasks.size()); //still 4, should not have affected Tasks
        
        WorkingCase.Move_Out_Date__c = null;
test.StartTest();
        update WorkingCase;
test.stopTest();        
        tasks = [select id from Task where WhatID = :WorkingCase.id and IsClosed != true and AVB_Type__c = 'Move Out Process'];
        system.assertEquals(0, tasks.size()); //should be closed now
        
    }
    
    static testmethod void testReschedMoveOut()
    {
        //Reschedule Move Out
        Account acc = [select id from Account limit 1];
        User u = [select id from User where IsActive = true limit 1];
        Case WorkingCase = new Case(
                RecordTypeID = MoveInMoveOut.casertmap().get('Move Out Tracking Process'),
                AccountID = acc.id,
                Origin = 'MRI Import',
                Status = 'New',
                Priority = 'Medium',
                Rejected__c = False,
                Reason = 'Notice To Vacate',
                Case_Primary_Type__c = 'Notice To Vacate',
                NTV_Date__c = system.today().addDays(-1),
                Move_Out_Date__c = system.today().addDays(10),
                Preliminary_Inspection_Date__c = system.now().addDays(5),
                OwnerID = u.id,
                AVB_Contact_Name__c = 'MRI Import'
            );
        
        
        insert WorkingCase;
        
        list<Task> tasks = [select id from Task where WhatID = :WorkingCase.id and IsClosed != true and AVB_Type__c = 'Move Out Process'];
        system.assertEquals(4, tasks.size()); //4 open Tasks on new Move Out
        
        WorkingCase.Status = 'Open'; //Case must be Open to be in Move Out
        update WorkingCase;
        
        tasks = [select id from Task where WhatID = :WorkingCase.id and IsClosed != true and AVB_Type__c = 'Move Out Process'];
        system.assertEquals(4, tasks.size()); //
        
        WorkingCase.Move_Out_Date__c = system.today().addDays(30);
test.StartTest();
        update WorkingCase;
test.stopTest();        
        tasks = [select id, ActivityDate, Subject_Sub_Category__c from Task where WhatID = :WorkingCase.id and IsClosed != true and AVB_Type__c = 'Move Out Process'];
        system.assertEquals(4, tasks.size()); //4 open Tasks on new Move Out
        for (Task t : tasks) {
            if (t.Subject_Sub_Category__c == 'Notice to Vacate Follow-up') system.assertEquals(WorkingCase.NTV_Date__c.addDays(2),t.ActivityDate);
            if (t.Subject_Sub_Category__c == 'Final Move Out Inspection/Estimates Inquiry') system.assertEquals(WorkingCase.Preliminary_Inspection_Date__c.date().addDays(2),t.ActivityDate);
            if (t.Subject_Sub_Category__c == 'Move Out Complete Follow Up') system.assertEquals(WorkingCase.Move_Out_Date__c.addDays(3),t.ActivityDate);
        }
        
    }
    
    static testmethod void testRejectMoveOut()
    {
        //Rejected Move Out
        Account acc = [select id from Account limit 1];
        User u = [select id from User where IsActive = true limit 1];
        Case WorkingCase = new Case(
                RecordTypeID = MoveInMoveOut.casertmap().get('Move Out Tracking Process'),
                AccountID = acc.id,
                Origin = 'MRI Import',
                Status = 'New',
                Priority = 'Medium',
                Rejected__c = False,
                Reason = 'Notice To Vacate',
                Case_Primary_Type__c = 'Notice To Vacate',
                NTV_Date__c = system.today().addDays(-1),
                Move_Out_Date__c = system.today().addDays(10),
                Preliminary_Inspection_Date__c = system.now().addDays(5),
                OwnerID = u.id,
                AVB_Contact_Name__c = 'MRI Import'
            );
        
        insert WorkingCase;
        list<Task> tasks = [select id from Task where WhatID = :WorkingCase.id and IsClosed != true and AVB_Type__c = 'Move Out Process'];
        system.assertEquals(4, tasks.size()); //4 open Tasks on new Move Out
        
        WorkingCase.Status = 'Open'; //Case must be Open to be in Move Out
        update WorkingCase;


        tasks = [select id from Task where WhatID = :WorkingCase.id and IsClosed != true and AVB_Type__c = 'Move Out Process'];
        system.assertEquals(4, tasks.size()); //still 4, should not have affected Tasks
        
        WorkingCase.Rejected__c = true;

test.StartTest();
system.debug('\n\nsendreject');
        update WorkingCase;
system.debug('\n\nsentreject');
test.stopTest();
        tasks = [select id from Task where WhatID = :WorkingCase.id and IsClosed != true and AVB_Type__c = 'Move Out Process'];
        system.assertEquals(0, tasks.size());//those Tasks should be closed now.
    }
    
    
    static testmethod void testOtherRecordType()
    {
        RecordType rt = [select id from RecordType 
            where SobjectType = 'Case' and Name != 'Move In Tracking Process' and Name != 'Move Out Tracking Process' limit 1];
        Account acc = [select id from Account limit 1];
        User u = [select id from User where IsActive = true limit 1];
        Case WorkingCase = new Case(
                RecordTypeID = rt.id,
                AccountID = acc.id,
                Origin = 'MRI Import',
                Status = 'New',
                Priority = 'Medium',
                Rejected__c = False,
                Reason = 'Some reason',
                Case_Primary_Type__c = 'Notice To Vacate',
                NTV_Date__c = system.today().addDays(-1),
                Move_Out_Date__c = system.today().addDays(10),
                OwnerID = u.id,
                AVB_Contact_Name__c = 'MRI Import'
            );
test.startTest();       
        insert WorkingCase;
test.StopTest();        
        list<Task> tasks = [select id from Task where WhatID = :WorkingCase.id and IsClosed != true and AVB_Type__c like 'Move%'];
        system.assertEquals(0, tasks.size()); //shouldn't be any Tasks on this Case
        
    }
    

}