src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Data imported from Foundation indicating that this Contact is the Primary Contact on this Customer Group</description>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Guest_Card__c.object
<CustomObject>
    <fields>
        <fullName>AVB_Associate__c</fullName>
        <label>AVB Associate</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guest Cards</relationshipLabel>
        <relationshipName>Guest_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <label>Primary Contact</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prospect_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prospect Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Guest Cards</relationshipLabel>
        <relationshipName>Guest_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Guest Card</label>
    <nameField>
        <label>Guest Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guest Cards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Test_ContactTrigger.cls
@istest
private class Test_ContactTrigger {

	static testmethod void testGuestCardFind()
	{
		ID cgrtid = [select Id from Recordtype where SOBjecttype = 'Account' and Name = 'Customer Group' limit 1].Id;
		
		list<Account> testcgs = new list<Account>();
		testcgs.add(new Account(
			Name = 'testperson and other occupants',
			RecordtypeID = cgrtid
			));
		insert testcgs;
		
		Guest_Card__c testgc = new Guest_Card__c(
			Prospect_Account__c = testcgs[0].Id,
			Name = testcgs[0].Name,
			AVB_Associate__c = 'test associate');
		insert testgc;
		
		Contact testcon = new Contact(
			AccountId = testcgs[0].Id,
			LastName = 'testcon',
			Primary_Contact__c = TRUE);
		
test.startTest();
		insert testcon;
		
test.stopTest();
		testgc = [select Contact__c from Guest_Card__c where Id = :testgc.Id];
		system.assertEquals(testcon.Id, testgc.Contact__c);
	}
}