src/objects/Guest_Card__c.object
<CustomObject>
    <fields>
        <fullName>AVB_Associate__c</fullName>
        <label>AVB Associate</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inactive_Reason__c</fullName>
        <label>Inactive Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Additonal Deposit/Guarantor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apt Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conviction of Felony</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Rating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment still pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Status Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Income Level</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Response/Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Moving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Objected to Community</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Objection to Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Objection to Floorplan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Object to Smoke-Free Community</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Rental Option</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pet Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shopping for Friend or Relative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unit Unavailable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Home to Sell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Inactivated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Initial_Lead_Type__c</fullName>
        <label>Initial Lead Type</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Chat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <description>If (Class ID=Community Target Class ID) AND (Expected Move in Date &lt;15 days away)=Hot;  Expected Move In Date&lt;30Days away=Warm;  else=Future</description>
        <label>Rating</label>
        <picklist>
            <picklistValues>
                <fullName>Hot</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Future</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Manually set to Active, Inactive or Wait list.  Leased will be set for you automatically</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wait List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leased</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>When_will_you_be_moving_in__c</fullName>
        <label>When will you be moving in?</label>
        <type>Date</type>
    </fields>
    <label>Guest Card</label>
    <nameField>
        <label>Guest Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guest Cards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/GuestCardsCheck.cls
global class GuestCardsCheck {
 /*
    Purpose:   - On a nightly basis, any Guest Cards that meet certain conditions will be 
               automatically changed to "Inactive" status. A scheduled class will call this 
               class method to perform this check.
          
    Created By:   Jeremy Scott (Synaptic) 1/26/2012
  
    Last Modified By:   Jeremy Nottingham (Synaptic) 2/15/12
        
    Current Version:   v1.1
  
    Revision Log:   v1.0 - (JS 1/26/2012) Set up class with header and methods
                    v1.1 - (JN 2/15/12) Change move in date field in query string, fix test method

  
  */    
  
    public static Date todayMinusThirty = system.Today().addDays(-30);
    public static Date todayMinusSixty = system.Today().addDays(-60);

/*
    public static Date todayMinusThirty = system.Today().addDays(-3);
    public static Date todayMinusSixty = system.Today().addDays(-6);
*/
         
    //public static String checkGCQuery = 'select Id from Guest_Card__c where Initial_Lead_Type__c = \'Independent Lead Source\''
    public static String checkGCQuery = 'select Id from Guest_Card__c where Initial_Lead_Type__c = \'Email\''
                                        + ' AND ((When_will_you_be_moving_in__c != Null AND LastActivityDate <= :todayMinusThirty)'
                                        + ' OR (When_will_you_be_moving_in__c = Null AND LastActivityDate <= :todayMinusSixty))';
    
    public static void checkGuestCards ()
    {
        
system.debug('\n\n30 checkGCQuery ' + checkGCQuery);
		if (Test.IsRunningTest())
			checkGCQuery += ' limit 100';
        //collect a list of records that need to be inactivated
        List <Guest_Card__c> InactiveGCs = Database.query(checkGCQuery);
        
        for (Guest_Card__c gc :InactiveGCs)
        {
            gc.Status__c = 'Inactive';
            //gc.Inactive_Reason__c = 'Non Response/Unknown';
            gc.Inactive_Reason__c = 'Auto Inactivated';
        }
        
        update inactiveGCs;  
    }
    
    
    public static testMethod void testGuestCardCheck() {  
        
        Guest_Card__c gc = new Guest_Card__c ();
           gc.Name = 'test';
           gc.Rating__c = '1';
           gc.Initial_Lead_Type__c = 'Independent Lead Source';
           gc.Inactive_Reason__c = null;
           gc.When_will_you_be_moving_in__c = null;
           gc.AVB_Associate__c = 'avb assoc';
           gc.Status__c = 'Active';
           insert gc;
           
test.startTest();       
        GuestCardsCheck.checkGCQuery = 'select Id from Guest_Card__c where id = \'' + gc.Id + '\'';
        GuestCardsCheck.checkGuestCards();
test.stopTest();
        
        gc = [select Status__c, Inactive_Reason__c from Guest_Card__c where Id = :gc.Id];
        system.assertEquals('Inactive', gc.Status__c);  
        system.assertEquals('Auto Inactivated', gc.Inactive_Reason__c); 
                
        
    }
}