src/objects/Guest_Card__c.object
<CustomObject>
    <fields>
        <fullName>AVB_Associate__c</fullName>
        <label>AVB Associate</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guest_Card_Details__c</fullName>
        <label>Guest Card Details</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Initial_Lead_Type__c</fullName>
        <label>Initial Lead Type</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Chat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Prospect_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prospect Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Guest Cards</relationshipLabel>
        <relationshipName>Guest_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <description>If (Class ID=Community Target Class ID) AND (Expected Move in Date &lt;15 days away)=Hot;  Expected Move In Date&lt;30Days away=Warm;  else=Future</description>
        <label>Rating</label>
        <picklist>
            <picklistValues>
                <fullName>Hot</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Future</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SHARED__c</fullName>
        <label>SHARED</label>
        <picklist>
            <picklistValues>
                <fullName>Yes - enter into MRI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Guest Card</label>
    <nameField>
        <label>Guest Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guest Cards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/RMACTION__c.object
<CustomObject>
    <description>MRI RMAction records</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RMActions</relationshipLabel>
        <relationshipName>RMActions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ActCode__c</fullName>
        <label>Action Type</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActDate__c</fullName>
        <label>Action Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ActDescription__c</fullName>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Guest_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guest Card</label>
        <referenceTo>Guest_Card__c</referenceTo>
        <relationshipLabel>RMActions</relationshipLabel>
        <relationshipName>RMActions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RMAction</label>
    <nameField>
        <label>RMACTION Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMActions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestRMActionTrig.cls
@istest
private class TestRMActionTrig {
	
	static testmethod void testRMActiontrig()
	{
		Datetime actdate = system.now().addDays(1);
		
		//test insert of RMA on Account with a non-shared (MRI) Guest Card
		Account a = new Account(Name = 'testacc');
		insert a;
		
		Guest_Card__c testgc = new Guest_Card__c(
			Prospect_Account__c = a.id,
			Shared__c = 'No',
			Rating__c = 'Hot',
			AVB_Associate__c = 'test person',
			Name = 'testgc');
		insert testgc;
		
		list<RMAction__c> testrmas = new list<RMAction__c>();
		testrmas.add(new RMAction__c(
			Account__c = a.id,
			ActCode__c = 'GC',
			ActDescription__c = 'test description',
			Name = 'testrma'));
		testrmas.add(new RMAction__c(
			Account__c = a.id,
			ActCode__c = 'AT',
			ActDate__c = actdate,
			Name = 'testrma'));
		testrmas.add(new RMAction__c(
			Account__c = a.id,
			ActCode__c = 'EM',
			Name = 'testrma'));
		
test.startTest();
		insert testrmas;
		
		//Verify that the RMAction was associated with the Guest Card
		testgc = [select id, Initial_Lead_Type__c, Guest_Card_Details__c, Rating__c,
			(select Id from RMActions__r),
			(select Id, AVB_Type__c, Subject_Sub_Category__c, StartDateTime from Events),
			(select Id, AVB_Type__c, Subject_Sub_Category__c, Status from Tasks where Status != 'Complete')
			from Guest_Card__c where id = :testgc.id];
		system.assertEquals(3, testgc.RMActions__r.size());
		system.assertEquals(1, testgc.Events.size());
		system.assertEquals(actdate, testgc.Events[0].StartDateTime);
		
		system.assertEquals('Email', testgc.Initial_Lead_Type__c);
		system.assertEquals('Warm', testgc.Rating__c);
		
		system.assertEquals('test description', testgc.Guest_Card_Details__c);
		
		testrmas = new list<RMAction__c>();
		testrmas.add(new RMAction__c(
			Account__c = a.id,
			ActCode__c = 'PH',
			Name = 'testrma'));
		testrmas.add(new RMAction__c(
			Account__c = a.id,
			ActCode__c = 'GC',
			ActDescription__c = 'addendum',
			Name = 'testrma'));
		insert testrmas;
		
		//Verify that the RMAction was associated with the Guest Card
		testgc = [select id, Initial_Lead_Type__c, Guest_Card_Details__c,
			(select Id from RMActions__r),
			(select Id, AVB_Type__c, Subject_Sub_Category__c, StartDateTime from Events)
			from Guest_Card__c where id = :testgc.id];
		system.assertEquals(5, testgc.RMActions__r.size());
		system.assertEquals(1, testgc.Events.size());
		
		system.assertEquals('Call', testgc.Initial_Lead_Type__c);
		system.assertEquals('test description addendum', testgc.Guest_Card_Details__c);
		
		testrmas = new list<RMAction__c>();
		testrmas.add(new RMAction__c(
			Account__c = a.id,
			ActCode__c = 'IT',
			Name = 'testrma'));
		insert testrmas;
		
		//Verify that the RMAction was associated with the Guest Card
		testgc = [select id, Initial_Lead_Type__c, Guest_Card_Details__c,
			(select Id from RMActions__r),
			(select Id, AVB_Type__c, Subject_Sub_Category__c, StartDateTime from Events)
			from Guest_Card__c where id = :testgc.id];
		system.assertEquals(6, testgc.RMActions__r.size());
		system.assertEquals(1, testgc.Events.size());
		
		system.assertEquals('Internet', testgc.Initial_Lead_Type__c);
		system.assertEquals('test description addendum', testgc.Guest_Card_Details__c);
		
		testrmas = new list<RMAction__c>();
		testrmas.add(new RMAction__c(
			Account__c = a.id,
			ActCode__c = 'WI',
			Name = 'testrma'));
		insert testrmas;
test.stopTest();
		
		//Verify that the RMAction was associated with the Guest Card
		testgc = [select id, Initial_Lead_Type__c, Guest_Card_Details__c,
			(select Id from RMActions__r),
			(select Id, AVB_Type__c, Subject_Sub_Category__c, StartDateTime from Events)
			from Guest_Card__c where id = :testgc.id];
		system.assertEquals(7, testgc.RMActions__r.size());
		system.assertEquals(2, testgc.Events.size());
		
		system.assertEquals('Walk In', testgc.Initial_Lead_Type__c);
		system.assertEquals('test description addendum', testgc.Guest_Card_Details__c);
		

	}
}